[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn promptapp.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 300