# Generated by Django 5.2.4 on 2025-07-24 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('template_used', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('subject', models.TextField(blank=True)),
                ('task', models.CharField(blank=True, max_length=200)),
                ('context', models.CharField(blank=True, max_length=100)),
                ('methodology', models.CharField(blank=True, max_length=200)),
                ('tone', models.CharField(blank=True, max_length=100)),
                ('enhancement_mode', models.CharField(choices=[('enhanced', 'Enhanced'), ('basic', 'Basic')], default='enhanced', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_time_seconds', models.FloatField(blank=True, null=True)),
                ('copied_to_clipboard', models.BooleanField(default=False)),
                ('improvement_requested', models.BooleanField(default=False)),
                ('improvement_applied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('pages_visited', models.IntegerField(default=1)),
                ('completion_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('partial', 'Partial'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('suggestion_text', models.TextField()),
                ('applied', models.BooleanField(default=False)),
                ('prompt_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.promptgeneration')),
            ],
        ),
        migrations.AddField(
            model_name='promptgeneration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.usersession'),
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=200)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.usersession')),
            ],
        ),
    ]
