# Generated by Django 5.2.4 on 2025-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptgeneration',
            name='generated_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
