# Generated by Django 5.2.4 on 2025-07-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_promptgeneration_actionability_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptgeneration',
            name='originality_score',
        ),
        migrations.RemoveField(
            model_name='promptgeneration',
            name='student_centeredness_score',
        ),
        migrations.RemoveField(
            model_name='promptgeneration',
            name='theory_integration_score',
        ),
    ]
