# Generated by Django 5.2.4 on 2025-07-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_remove_promptgeneration_originality_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptgeneration',
            name='subject_category',
            field=models.CharField(blank=True, choices=[('STEM', 'Science, Technology, Engineering, Math'), ('Humanities', 'Language Arts, Social Studies, History'), ('Languages', 'Language Learning & Literature'), ('Arts', 'Creative Arts, Music, Drama'), ('PE_Health', 'Physical Education & Health'), ('Life_Skills', 'Personal Development & Life Skills'), ('Vocational', 'Career & Technical Education'), ('Cross_Curricular', 'Multiple Subjects'), ('Other', 'Other/Unspecified')], max_length=50),
        ),
    ]
