# Generated by Django 5.2.4 on 2025-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_alter_promptgeneration_subject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptgeneration',
            name='innovation_level',
            field=models.CharField(blank=True, choices=[('Conservative', 'Prefers traditional methods'), ('Moderate', 'Balanced approach'), ('Innovative', 'Embraces new methodologies'), ('Experimental', 'Cutting-edge approaches')], max_length=20, null=True),
        ),
    ]
