# Generated by Django 5.2.4 on 2025-07-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_alter_promptgeneration_innovation_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptgeneration',
            name='innovation_level',
        ),
        migrations.AddField(
            model_name='promptgeneration',
            name='selected_theory',
            field=models.CharField(blank=True, choices=[('blooms', "Bloom's Taxonomy"), ('udl', 'UDL Principles'), ('tpack', 'TPACK Framework'), ('constructivist', 'Constructivist Learning'), ('social_learning', 'Social Learning Theory'), ('scaffolding', 'Scaffolding'), ('differentiation', 'Differentiated Instruction')], help_text='Which educational theory was applied to enhance the prompt', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='promptgeneration',
            name='theory_application_quality',
            field=models.FloatField(blank=True, help_text='Quality score (0-10) for how well the theory was applied in context', null=True),
        ),
        migrations.AddField(
            model_name='promptgeneration',
            name='theory_auto_suggested',
            field=models.BooleanField(default=False, help_text='True if theory was auto-suggested by system, False if manually selected by user'),
        ),
        migrations.AddField(
            model_name='promptgeneration',
            name='theory_learning_indicator',
            field=models.CharField(blank=True, choices=[('novice', 'Shows basic understanding of theories'), ('developing', 'Demonstrates growing theory knowledge'), ('proficient', 'Uses theories appropriately and effectively'), ('expert', 'Shows sophisticated theory integration')], help_text="User's apparent level of educational theory knowledge", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='promptgeneration',
            name='theory_suggestion_accuracy',
            field=models.CharField(blank=True, choices=[('accepted', 'User accepted auto-suggestion'), ('modified', 'User chose different theory than suggested'), ('ignored', 'User chose no theory when suggestion was made'), ('manual', 'User selected theory without seeing suggestion')], help_text='How user responded to system theory suggestions', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='promptgeneration',
            name='user_theory_preference',
            field=models.CharField(blank=True, choices=[('consistent', 'Always uses same theory'), ('varied_appropriate', 'Uses different theories appropriately'), ('experimental', 'Tries various theories to learn'), ('conservative', 'Sticks to basic theories'), ('advanced', 'Prefers complex/specialized theories')], help_text="Pattern analysis of user's theory selection behavior over time", max_length=30, null=True),
        ),
    ]
