# Generated by Django 5.2.4 on 2025-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_remove_promptgeneration_innovation_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='ai_experience',
            field=models.CharField(blank=True, choices=[('none', 'No experience'), ('basic', 'Basic (e.g., ChatGPT)'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text="User's self-reported AI tools experience level", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='onboarding_completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='onboarding_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='research_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='teaching_years',
            field=models.CharField(blank=True, choices=[('0-5', '0-5 years'), ('6-15', '6-15 years'), ('16-25', '16-25 years'), ('25+', '25+ years')], help_text='Years of teaching experience', max_length=10, null=True),
        ),
    ]
