# Generated by Django 5.2.4 on 2025-08-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_usersession_ai_experience_usersession_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='follow_up_email',
            field=models.EmailField(blank=True, help_text='Email for AI education research participation', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='research_interview_interest',
            field=models.BooleanField(default=False, help_text='Interest in participating in research interview'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='training_interests',
            field=models.JSONField(blank=True, default=list, help_text='List of all training areas the user is interested in'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='training_needs_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='training_needs_completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='training_needs_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='training_other_needs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='training_priorities',
            field=models.JSONField(blank=True, default=dict, help_text="Dictionary with priority rankings: {'area': priority_number}"),
        ),
    ]
